receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15
  resourcedetection:
    # Reads resource information from the OTEL_RESOURCE_ATTRIBUTES environment variable.
    detectors: ["env"]
    timeout: 2s
  batch:
    send_batch_size: 10000
    timeout: 10s

exporters:
  logging:
    # detailed | normal | basic
    verbosity: basic
    sampling_initial: 2
    sampling_thereafter: 500
  otlp/jaeger:
    endpoint: "localhost:14317"
    tls:
      insecure: true
    

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [logging, otlp/jaeger]