receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
        cors:
          allowed_origins:
          - http://localhost:5173 # from ui

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15
  resourcedetection:
    # Reads resource information from the OTEL_RESOURCE_ATTRIBUTES environment variable.
    detectors: ["env"]
    timeout: 2s
  batch:
    send_batch_size: 10000
    timeout: 10s

exporters:
  logging:
    # detailed | normal | basic
    verbosity: basic
    sampling_initial: 2
    sampling_thereafter: 500
  otlp/jaeger:
    endpoint: "localhost:14317"
    tls:
      insecure: true
  otlphttp/openobserve:
  # Use traces_endpoint instead of endpoint
    traces_endpoint: http://localhost:5080/api/default/traces
    tls:
      insecure: true
    headers:
      # Got from UI /web/ingestion/traces/opentelemetry
      Authorization: "Basic cm9vdEB5bWd5dC5pbzpJVUxEekU1cVN2ZUI0QjNa"
    
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [logging, otlphttp/openobserve]