[env]
GRAPHQL_HOST = "http://localhost:8000"
GRAPHQL_ENDPOINT = "${GRAPHQL_HOST}/graphql"
GRAPHQL_CLIENT_PROJECT = "rust/client"
GRAPHQL_SCHEMA_PATH = "${GRAPHQL_CLIENT_PROJECT}/schema.json"
GRAPHQL_QUERY_PATH = "${GRAPHQL_CLIENT_PROJECT}/query.gql"
GRAPHQL_GENERATE_PATH = "${GRAPHQL_CLIENT_PROJECT}/src/generated"

REST_HOST = "http://localhost:8001"

# init task is reserved task
# https://github.com/sagiegurari/cargo-make#init-and-end-tasks
[tasks."project:init"]
run_task = [
  { name = ["init:submodule", "rest:init", "ui:init"] }
]

[tasks."init:submodule"]
command = "git"
args = [
  "submodule", "update", "--init", "--recursive"
]

[tasks."graphql:run"]
cwd = "rust/graphql"
command = "cargo"
args = [ "run" ]

[tasks."graphql:schema"]
command = "graphql-client"
install_crate = {  crate_name = "graphql_client_cli",  binary = "graphql-client",  test_arg = "--version",  min_version = "0.12.0" }
args = ["introspect-schema", "${GRAPHQL_ENDPOINT}"]

[tasks."graphql:schema:update"]
script = '''
cargo make --quiet graphql:schema > "${GRAPHQL_SCHEMA_PATH}"
echo "Update graphql schema ${GRAPHQL_SCHEMA_PATH}" 
'''

[tasks."graphql:generate"]
command = "graphql-client"
args = [
  "generate", 
  "--schema-path", "${GRAPHQL_SCHEMA_PATH}",
  "--output-directory", "${GRAPHQL_GENERATE_PATH}",
  "${GRAPHQL_QUERY_PATH}"
]

[tasks."request:graphql"]
env = { "HOST" = "http://localhost:8000" }
run_task = [
  { name = "request:scenario:once" }
]

[tasks."request:rest"]
env = { "HOST" = "http://localhost:8001" }
run_task = [
  { name = "request:scenario:once" }
]

[tasks."request:scenario:once"]
cwd = "rust/client"
command = "cargo"
args = [
  "run", "--",
  "--host", "${HOST}", 
  "--users","1",
  "--iterations", "1", 
  "--scenarios", "${SCENARIO}",
]

[tasks."collector:run"]
cwd = "collector/cmd/otelcontribcol"
command = "go"
args = [
  "run", "main.go", "components.go", "main_others.go",
  "--config", "../../../collector-config.yaml"
]

[tasks."jaeger:run"]
command = "docker"
args = [
  "run", "--rm",
  "--name", "jaeger",
  "--env", "COLLECTOR_OTLP_ENABLED=true",
  "--publish", "16686:16686",
  "--publish", "14317:4317",
  "jaegertracing/all-in-one:1.44",
]

[tasks."rest:init"]
cwd = "python/rest"
command = "poetry"
args = [ "install" ]

[tasks."rest:run"]
cwd = "python/rest"
command = "poetry"
args = [
  "run", "python", "main.py"
]

[tasks."ui:init"]
cwd = "typescript/ui"
command = "yarn"
args = ["install"]

[tasks."ui:run"]
cwd = "typescript/ui"
command = "yarn"
args = ["dev"]
